version: "3"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=public_user
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=shopping
      - POSTGRES_HOST=localhost


